version: '3.1'

services:
  app:
    build:
      dockerfile: ./docker/data/Dockerfile
    ports:
      - 8081:80
    labels:
     - "traefik.http.routers.app.rule=Host(`app.localhost`)"

    volumes:
      - ./data:/var/www/html/
      - ./docker/data/000-default.conf:/etc/apache2/site-enabled/000-default.conf
    networks:
      - default

  # admin:
  #   build:
  #     dockerfile: ./docker/admin/Dockerfile
  #   ports:
  #     - 8082:80
  #   labels:
  #    - "traefik.http.routers.admin.rule=Host(`admin.localhost`)"
  #   volumes:
  #     - ./admin:/var/www/html/
  #     - ./docker/admin/000-default.conf:/etc/apache2/site-enabled/000-default.conf
  #   networks:
  #     - default

  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: apachedb_dev
      MARIADB_USER: apachedb_user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql
    ports:
      - 8085:80
    volumes:
      - /sessions
    networks:
      - default

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  traefik:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
